name: CI
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install packages
        run: pnpm pnpm install
      - name: Run lint
        run: pnpm run lint
      - name: Run tests
        run: pnpm test
      - name: Upload Test coverage report
        uses: actions/upload-artifact@v1
        with:
          name: Coverage
          path: coverage/
